name: Auto Format and Fix All Files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format-and-fix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Super-Linter and Auto Fixer
      uses: super-linter/super-linter/designate@v7
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
