name: Auto Format and Fix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Prettier Formatter
      uses: crey08/gofmt-action@v2.3.0
      continue-on-error: true
      with:
        gofmt-path: '.'
